### ISSUE TITLE
If that's not discrimination idk what is

### ISSUE THREAD

**Issue by BikoKiessling** [wolkoman/gntmhub#1]
Evaluating a humans beauty shouldn't be determined merely by looks. This is outrageously ignorant of the most inner core values which shine much brighter than anything you may perceive on one's surface. Thus, I hereby declare this project as sexist, superficial and discriminating. I mean, where's the handsome boys in all of this?

Oh and I think human trade isn't legal anymore either. 

K, thx bye

**Comment by wolkoman** [comment]
Thank you for your concern!

I have wrestled with this issue for a long time and will therefore ressign from position as Chief Moral Officer effective immediately. Its been a blessing to get a glimpse into the modelling world and to see all these strong powerful women in all their shapes and sizes. 
To not endanger the success of the project I will stay in the position of Software Engineer. Here at GNTMHUB we believe that just firing random management personal,can relief problems that in reality stem from societies darkest sides and could otherwise only be solved by a fair and open discussion about the way we treat each other.

Thanks to all the wonderful people I got to work with!

**Comment by BikoKiessling** [comment]
Do you really think stepping down is gonna solve the issue? As you've said, we're being faced with a mere symptom of the actual issue here. Morals are for losers. I prefer action! Let's storm the GNTM capitol and set a definite long awaited end to this tragedy!!!

**Comment by wolkoman** [comment]
This is the automated GitHub Issues bot here *biep bop*!
Please do not comment on closed issues as it is illegal. You can find more information about this policy here: https://bit.ly/36DNC20
